name: fl
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - nvidia::cudatoolkit=10.2
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - wandb
    - numpy==1.22.2
    - termcolor==1.1.0
    - tensorboard==2.8.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - ipdb==0.13.9
    - yapf==0.31.0
    - sklearn==0.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - git+https://github.com/RobustBench/robustbench.git
